### ISSUE TITLE
Gnome 45 version

### ISSUE THREAD

**Issue by eindgebruiker** [spybug/NotifyFilter-GnomeExtension#3]
Do you have any plans for a gnome 45 version?
Do you need any help?

**Comment by zdrapela** [comment]
For me, just adding the Gnome 45 to supported versions worked. You can achieve that by editing `~/.local/share/gnome-shell/extensions/notification-filter@asynclink.org/metadata.json`

I opened a pull request for that: https://github.com/spybug/NotifyFilter-GnomeExtension/pull/4

**Comment by eindgebruiker** [comment]
Porting to 44 is indeed easy. Porting to 45 involves a bit more work https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by spybug** [comment]
I've updated to only add support for v44 now and it's been uploaded to the gnome extensions site. Indeed it looks like v45 will be more work to support and isn't backwards compatible.

**Comment by toolstack** [comment]
@spybug I've ported the extension to 45, see PR #5.

Let me know if you have any questions or want any changes.

**Comment by eindgebruiker** [comment]
@toolstack Thank you! I installed the ported extension. Working fine so far. As documented in the PR the settings window has 100 (empty) filters by default, instead of the option to create new filters one by one.

**Comment by toolstack** [comment]
@eindgebruiker Np, if @spybug doesn't reply in a week or so I'll look into forking and publish it to extensions.gnome.org myself.

**Comment by spybug** [comment]
I tried to upload the v45 version to the extension store, but had some issues during the review:

The reviewer's reply was:
>1. `lookupByURL()` is a bad practice. You can use `this.getSettings()` instead (line 21 `extension.js`).
>2. Dont' hold any instances after window close (line 10-15 `prefs.js`):
>    [EGO Review Guidelines: Destroy](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#destroy-all-objects)
>    I recommend to make them local to `fillPreferencesWindow()` and pass them to the other methods and functions.

**Comment by spybug** [comment]
v45 has been approved on the extension store now, thanks for doing this! 

https://extensions.gnome.org/extension/5380/notification-filter/
